### ISSUE TITLE
Build broken with Alfresco Enterprise 4.1.3

### ISSUE THREAD

**Issue by OpenPj** [philipmeadows/alfresco-webscript-manifold-connector#2]
Trying to build the connector with Alfresco Enterprise 4.1.3 returns the following exception:

[ERROR] Failed to execute goal on project mcf-alfresco-webscript-connector: Could not resolve dependencies for project org.apache.manifoldcf:mcf-alfresco-webscript-connector:jar:1.1.1: Failed to collect dependencies for [org.alfresco.enterprise:alfresco-solr-integration:jar:4.1.3 (compile), org.alfresco.enterprise:alfresco-core:jar:4.1.3 (compile), org.apache.manifoldcf:mcf-core:jar:1.1.1 (provided), org.apache.manifoldcf:mcf-agents:jar:1.1.1 (provided), org.apache.manifoldcf:mcf-pull-agent:jar:1.1.1 (provided), org.apache.manifoldcf:mcf-ui-core:jar:1.1.1 (provided)]: Failed to read artifact descriptor for woodstox:wstx-asl:jar:3.2.7: Could not transfer artifact woodstox:wstx-asl:pom:3.2.7 from/to alfresco-internal (https://artifacts.alfresco.com/nexus/content/groups/internal): Not authorized , ReasonPhrase:Unauthorized. -> [Help 1]

**Comment by maoo** [comment]
I guess this issue can be closed, having switched to a new project structure (see branch custom-webscripts)
