### ISSUE TITLE
Text extracting

### ISSUE THREAD

**Issue by alexist** [philipmeadows/alfresco-webscript-manifold-connector#21]
Hi,

ManifoldCF use extract update handler to handle binary content. Binary content is sent to solr, and tikka try to extract text content and some metadata (mime type).

For alfresco connector, Alfresco should be used to convert binary to text as official solr do (by calling NodeContentGet). Because alfresco already know how to convert document to text. 

But NodeContentGet webscript is protected by Certificat, you have to clone this webscript.

**Comment by maoo** [comment]
Created issue https://github.com/maoo/alfresco-indexer/issues/1
